### ISSUE TITLE
Clone repo to create "terraform-aws-eks-cluster"

### ISSUE THREAD

**Issue by eddie-knight** [finos/cfi-terraform-template-child-module#13]
Need confirmation from @ml4 that this is the correct name. 

The repo will be used to house aws-eks specific logic that does not include peripherals. The child module will then be integrated into the final EKS module that we are working toward.

Assigning to @TheJuanAndOnly99 for actioning as soon as Mark confirms the desired name.

**Comment by eddie-knight** [comment]
We will want a way to deploy EKS along with it's peripherals... so we'll need a way to differentiate between the fully compliant (hardened) root EKS module & the child module that just addresses the cluster specifically.

We already have a [terraform-aws-eks](https://github.com/finos/terraform-aws-eks) which was not created from this child-module repo template. We can modify/delete that repo if needed.

I'd like us to leave this conversation with a replicable process... @ml4 could you share more thoughts in response to my notes above?

**Comment by mcleo-d** [comment]
To be moved forward by @ml4, @eddie-knight and @thinkl33t as discussed on https://github.com/finos/compliant-financial-infrastructure/issues/265

**Comment by eddie-knight** [comment]
On the call today we discussed naming the repo `terraform-aws-cfi-eks` to enable differentiation when the module is pushed to the [Terraform Registry](https://registry.terraform.io/). 

Do we have any other suggestions to consider?

**Comment by eddie-knight** [comment]
This was completed by renaming another repo
