### ISSUE TITLE
Please generate terraform-azurerm-cfi-aks from template cfi-terraform-template-child-module #14

### ISSUE THREAD

**Issue by ml4** [finos/cfi-terraform-template-child-module#15]
## Support Question

Title: Create repo: terraform-azurerm-cfi-aks
Subject: Terraform child module deploying compliant AKS instance.

@TheJuanAndOnly99 @eddie-knight @thinkl33t @AdrianHammond @maoo

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight @ml4 Repo created https://github.com/finos/terraform-azurerm-cfi-aks
