### ISSUE TITLE
Please generate terraform-azurerm-cfi-postgresql from template cfi-terraform-template-child-module

### ISSUE THREAD

**Issue by ml4** [finos/cfi-terraform-template-child-module#18]
## Support Question

Title: Create repo: terraform-azurerm-cfi-postgresql
Subject: Terraform child module deploying a compliant Azure Database for PostgreSQL instance.

@TheJuanAndOnly99 @eddie-knight @thinkl33t @AdrianHammond @maoo

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight @ml4 Repo created https://github.com/finos/terraform-azurerm-cfi-postgresql
