### ISSUE TITLE
Please generate terraform-aws-cfi-sqs from template cfi-terraform-template-child-module

### ISSUE THREAD

**Issue by ml4** [finos/cfi-terraform-template-child-module#20]
## Support Question

Title: Create repo: terraform-aws-cfi-sqs
Subject: Terraform child module deploying a compliant AWS SQS instance.

@TheJuanAndOnly99 @eddie-knight @thinkl33t @AdrianHammond @maoo

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight @ml4 Repo created https://github.com/finos/terraform-aws-cfi-sqs
