### ISSUE TITLE
Add a Terraform specific static scanning tool.

### ISSUE THREAD

**Issue by abdullahgarcia** [finos/cfi-terraform-template-child-module#3]
### Description of Problem:

We need a Terraform specific static scanning tool besides the current code static scanning tool: semgrep.

### Potential Solutions:

An option is tfsec: https://github.com/aquasecurity/tfsec

**Comment by ml4** [comment]
Agree scanning is a good idea, but slightly concerned that we choose a tool, and then we get an opinionated result which would cost members time were they to use a different tool.

**Comment by eddie-knight** [comment]
I agree with the sentiment @ml4, but for the sake of moving the needle on the OpenSSF compliance OKR, I've pushed #10 to include mao's suggestion. Follow up discussion or PRs are absolutely welcome.
