### ISSUE TITLE
Update `README` and set `cfi-terraform-template-child-module` `public`

### ISSUE THREAD

**Issue by mcleo-d** [finos/cfi-terraform-template-child-module#8]
## Description

Update `README` for `cfi-terraform-template-child-module` so the repo can be switched from `private` to `public`

- [x] Create `README`
- [x] Switch repo from `private` to `public`
- [ ] Consider removing `-child-module` suffix from repo name

**Comment by eddie-knight** [comment]
@maoo That sounds fine to me, but I'd like to hear from @ml4 or @devops-adeel if they're able to respond today. 

Barring additional feedback, I'm fine with implementing the change.

**Comment by ml4** [comment]
`cfi-terraform-template-child-module` sorts minus-delimited fields by org, tool, function and result in that order and maps as close to tool, provider, function as I could get. We will scale so need a nomenclature IMHO.

**Comment by eddie-knight** [comment]
@maoo -- considering that it's Mark's opinion that more templates may be needed, I'd like to delay any potential renaming until the dust settles. Closing this issue as complete, and we can revisit the name change if no additional templates are needed.
